### ISSUE TITLE
Problem on upload AWSSDK 2.1.2

### ISSUE THREAD

**Issue by rbk1001** [cloudify-incubator/cloudify-awssdk-plugin#122]
when trying to upload the awssdk 2.1.2 plugins, error presented. is there any idea on how to resolve it?

# cfy plugins upload /root/awssdk_2.1.2/cloudify_awssdk_plugin-2.1.2-py27-none-linux_x86_64-redhat-Maipo.wgn -y /root/awssdk_2.1.2/plugin.yaml 
Creating plugin zip archive..
Uploading plugin archive (wagon + yaml)..
 tmpkqquf0.zip |#######################################################| 100.0%
An error occurred on the server: 400: Failed during plugin installation.(PluginDistributionNotSupported: Plugin `<Plugin id=`f0fa6cf1-c7ce-47ac-8ddb-df4ac87c6d3b` tenant=`default_tenant`>` is not supported for the manager platform or distribution.)
#

**Comment by EarthmanT** [comment]
It appears that you are installing a RedHat Maipo wagon on another platform.
