### ISSUE TITLE
Object status requested in decorator, before state is actually updated

### ISSUE THREAD

**Issue by dandrushko** [cloudify-incubator/cloudify-awssdk-plugin#129]
Immediately after the AWS object creation in the _wait_for_status_ decorator here
https://github.com/cloudify-incubator/cloudify-awssdk-plugin/blob/a8470c8393adca8cef9f214c5eb3742a6d6819e8/cloudify_awssdk/common/decorators.py#L159
there is a call to the object status:
https://github.com/cloudify-incubator/cloudify-awssdk-plugin/blob/a8470c8393adca8cef9f214c5eb3742a6d6819e8/cloudify_awssdk/common/decorators.py#L161

However at this moment _iface_ object itself wasn't updated with information from the recent result, as this happens in the outer decorator _aws_resource_ . As a result in a best case unnecessary retry happens, in the worst case workflow fails, steps to reproduce presented here - https://github.com/cloudify-incubator/cloudify-awssdk-plugin/issues/128

**Comment by EarthmanT** [comment]
Fixed in #132
