### ISSUE TITLE
CloudWatch Log Group support

### ISSUE THREAD

**Issue by 01000101** [cloudify-incubator/cloudify-awssdk-plugin#79]
We need to support adding Cloudwatch Log Groups -> https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_group.html

**Comment by EarthmanT** [comment]
This is available [here](https://github.com/cloudify-incubator/cloudify-boto3-plugin/tree/5ef4f8632a84ac8c62b2a2ad19b6703eee8d75f6).

Can you look at the [example](https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/add-logs/examples/cloudwatch-feature-demo/cloudwatch-logs.yaml) and let me know if it works for you?
