### ISSUE TITLE
Typo in legacy VPC node type?

### ISSUE THREAD

**Issue by tsznuk** [cloudify-incubator/cloudify-awssdk-plugin#93]
Shouldn't this line:

https://github.com/cloudify-incubator/cloudify-awssdk-plugin/blob/a22fb815ed84c98830b948b9663f29f194ceaedf/cloudify_awssdk/ec2/resources/routetable.py#L35

say 'VPC'  instead of 'Vpc'?

I think this typo prevents the route table from detecting connected legacy VPC nodes.

See #94

**Comment by EarthmanT** [comment]
Thanks.

**Comment by EarthmanT** [comment]
Fixed in [#94](https://github.com/cloudify-incubator/cloudify-awssdk-plugin/pull/94)
